# Generated by Django 3.2.16 on 2022-10-31 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20221021_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='music',
            field=models.CharField(blank=True, choices=[('60s', 'Sixties'), ('70s', 'Seventies'), ('80s', 'Eighties'), ('90s', 'Nineties'), ('Pop', 'Pop'), ('Synthpop', 'Synthpop'), ('Disco', 'Disco'), ('New Wave', 'Newwave'), ('Dark Wave', 'Darkwave'), ('Industrial', 'Industrial'), ('Punk', 'Punk'), ('Rock', 'Rock'), ('Indie', 'Indie'), ('Emo', 'Emo'), ('Grunge', 'Grunge'), ('Metal', 'Metal'), ('Blues', 'Blues'), ('Jazz', 'Jazz'), ('Classical', 'Classical'), ('Country', 'Country'), ('Folk', 'Folk'), ('Hip-hop', 'Hiphop'), ('Trip-hop', 'Triphop'), ('Trap', 'Trap'), ('Reggae', 'Reggae'), ('Soul', 'Soul'), ('R&B', 'Rnb'), ('Techno', 'Techno'), ('House', 'House'), ('Trance', 'Trance'), ('Drum & Bass', 'Drumandbass'), ('EDM', 'Edm'), ('EBM', 'Ebm'), ('K-Pop', 'Kpop'), ('J-Pop', 'Jpop'), ('Latin', 'Latin'), ('None', 'None'), ('Other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='event',
            name='sports',
            field=models.CharField(blank=True, choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Tennis', 'Tennis'), ('Volleyball', 'Volleyball'), ('Handball', 'Handball'), ('Badminton', 'Badminton'), ('Swimming', 'Swimming'), ('Boxing', 'Boxing'), ('Tabletennis', 'Tabletennis'), ('Skiing', 'Skiing'), ('Ice skating', 'Iceskating'), ('Roller skating', 'Rollerskating'), ('Cricket', 'Cricket'), ('Rugby', 'Rugby'), ('Darts', 'Darts'), ('Bowling', 'Bowling'), ('Hockey', 'Hockey'), ('Ice hockey', 'Icehockey'), ('Karate', 'Karate'), ('Horse riding', 'Horseriding'), ('Snowboarding', 'Snowboarding'), ('Skateboarding', 'Skateboarding'), ('Cycling', 'Cycling'), ('Archery', 'Archery'), ('Gymnastics', 'Gymnastics'), ('Figureskating', 'Figureskating'), ('Rockclimbing', 'Rockclimbing'), ('Bouldering', 'Bouldering'), ('Judo', 'Judo'), ('Kickboxing', 'Kickboxing'), ('Wrestling', 'Wrestling'), ('Jujutsu', 'Jujutsu'), ('MMA', 'Mma'), ('Taekwondo', 'Taekwondo'), ('Aikido', 'Aikido'), ('Fencing', 'Fencing'), ('Golf', 'Golf'), ('Dancing', 'Dancing'), ('Fishing', 'Fishing'), ('Rowing', 'Rowing'), ('Fitness', 'Fitness'), ('None', 'None'), ('Other', 'Other')], max_length=50),
        ),
    ]
