# Generated by Django 3.2.16 on 2022-10-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20221031_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='languages',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('German', 'German'), ('French', 'French'), ('Dutch', 'Dutch'), ('Turkish', 'Turkish'), ('Polish', 'Polish'), ('Spanish', 'Spanish'), ('Italian', 'Italian'), ('Portugese', 'Portugese'), ('Ukrainian', 'Ukrainian'), ('Russian', 'Russian'), ('Arabic', 'Arabic'), ('Chinese', 'Chinese'), ('Japanese', 'Japanese'), ('Korean', 'Korean'), ('Romanian', 'Romanian'), ('Swedish', 'Swedish'), ('Norwegian', 'Norwegian'), ('Danish', 'Danish'), ('Finnish', 'Finnish'), ('Hungarian', 'Hungarian'), ('Slovenian', 'Slovenian'), ('Estonian', 'Estonian'), ('Bulgarian', 'Bulgarian'), ('Latvian', 'Latvian'), ('Croatian', 'Croatian'), ('Greek', 'Greek'), ('Urdu', 'Urdu'), ('Hindi', 'Hindi'), ('Other', 'Other')], max_length=50),
        ),
    ]
