# Generated by Django 3.2.16 on 2022-10-29 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recommendation',
            name='location_mapbox',
        ),
    ]
